### ISSUE TITLE
ExecuteQueryAsync doesn't return IEnumerable<WorkItemReference>

### ISSUE THREAD

**Issue by stusklinar** [BerserkerDotNet/VSTS.Net#11]
As per the API spec - the `ExecuteQueryAsync(..)` doesn't return a list of `WorkItemReference` 

[https://docs.microsoft.com/en-us/rest/api/vsts/wit/wiql/query%20by%20wiql?view=vsts-rest-4.1#workitemqueryresult](https://docs.microsoft.com/en-us/rest/api/vsts/wit/wiql/query%20by%20wiql?view=vsts-rest-4.1#workitemqueryresult)

**Comment by BerserkerDotNet** [comment]
It actually does but in a different type :) What you get from the ExecuteQueryAsync is a base type for the query result, there are also to concrete types that are actually returned from the query, [FlatWorkItemsQueryResult](https://github.com/BerserkerDotNet/VSTS.Net/blob/master/src/VSTS.Net/Models/WorkItems/FlatWorkItemsQueryResult.cs) and [HierarchicalWorkItemsQueryResult](https://github.com/BerserkerDotNet/VSTS.Net/blob/master/src/VSTS.Net/Models/WorkItems/HierarchicalWorkItemsQueryResult.cs). There is a list of WorkItemReferences in the FlatWorkItemsQueryResult. 

I see now that this is really confusing and I'll change it soon to be something like:
`ExecuteFlatQueryAsync` and `ExecuteHierarchicalQueryAsync`.

**Comment by stusklinar** [comment]
Ahhhhh gotcha!
