### ISSUE TITLE
Change injection of HTTPClient to the HTTPFactoryies

### ISSUE THREAD

**Issue by stusklinar** [BerserkerDotNet/VSTS.Net#8]

**Comment by BerserkerDotNet** [comment]
Hi @stusklinar,
Thank you for submitting the issue.

Can you give more information on the use case where you need [IHttpClientFactory](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.ihttpclientfactory?view=aspnetcore-2.1), please?

I guess you want to customize the HttpClient in some way, it would help to know what customizations you need to implement this correctly.

**Comment by stusklinar** [comment]
@BerserkerDotNet - no customisations, just the recommendation moving forward for net2.1 from MS.

I've implemented this in a fork here - https://github.com/stusklinar/VSTS.Net

**Comment by stusklinar** [comment]
Well, you don't *use* IHttpClientFactory directly, it just injects a HttpClient for the the `Services.AddHttpService(..)` method.

I'll drop a link
